#!/usr/bin/env bash
# lib/dnsmasq.sh - DHCP/TFTP configuration via dnsmasq and boot configs

# ═══════════════════════════════════════════════════════════════════════════════
# dnsmasq Configuration
# ═══════════════════════════════════════════════════════════════════════════════

write_dnsmasq_config() {
    info "Writing dnsmasq configuration..."
    
    # Ensure we have network info
    if [[ -z "${SERVER_IP:-}" ]] || [[ -z "${DEFAULT_IF:-}" ]]; then
        detect_network_interface_and_ip
    fi
    
    if [[ "${DRY_RUN:-false}" == true ]]; then
        info "[DRY-RUN] Would write dnsmasq config to $DNSMASQ_CONF"
        info "[DRY-RUN] DHCP range: $DHCP_RANGE_START - $DHCP_RANGE_END"
        return 0
    fi
    
    # Write configuration
    cat > "$DNSMASQ_CONF" <<EOF
# ═══════════════════════════════════════════════════════════════════════════════
# PXE Server dnsmasq configuration
# Generated by pxe-server installer on $(date)
# ═══════════════════════════════════════════════════════════════════════════════

# Interface binding (bind only to PXE interface to avoid systemd-resolved conflict)
interface=$DEFAULT_IF
except-interface=lo
bind-interfaces

# Domain
domain=pxe.local

# ───────────────────────────────────────────────────────────────────────────────
# DHCP Configuration
# ───────────────────────────────────────────────────────────────────────────────
dhcp-range=${DHCP_RANGE_START},${DHCP_RANGE_END},${DHCP_NETMASK},${DHCP_LEASE}

# Gateway (option 3) and DNS (option 6) - both point to PXE server
dhcp-option=3,$SERVER_IP
dhcp-option=6,$SERVER_IP

# No upstream DNS - clients are isolated and only access NFS
# (PXE server can use its own DNS for setup purposes)

# ───────────────────────────────────────────────────────────────────────────────
# TFTP Configuration
# ───────────────────────────────────────────────────────────────────────────────
enable-tftp
tftp-root=$TFTP_ROOT

# ───────────────────────────────────────────────────────────────────────────────
# PXE Boot Configuration
# ───────────────────────────────────────────────────────────────────────────────

# Default BIOS boot
dhcp-boot=/bios/pxelinux.0

# UEFI x86_64 detection (architecture 7 = EFI BC, 9 = EFI x86_64)
dhcp-match=set:efi64,option:client-arch,7
dhcp-match=set:efi64,option:client-arch,9
dhcp-boot=tag:efi64,/grub/bootx64.efi

# Logging (optional - uncomment for debugging)
# log-dhcp
# log-queries
EOF
    
    # Restart dnsmasq to apply
    info "Restarting dnsmasq..."
    if ! systemctl restart dnsmasq; then
        error "Failed to restart dnsmasq"
        error "Check configuration with: dnsmasq --test"
        abort "dnsmasq restart failed"
    fi
    
    log_success "dnsmasq configured and restarted"
}

# ═══════════════════════════════════════════════════════════════════════════════
# PXELINUX Configuration (BIOS)
# ═══════════════════════════════════════════════════════════════════════════════

write_pxelinux_cfg() {
    info "Writing PXELINUX boot menu..."
    
    if [[ -z "${SERVER_IP:-}" ]]; then
        detect_network_interface_and_ip
    fi
    
    if [[ "${DRY_RUN:-false}" == true ]]; then
        info "[DRY-RUN] Would write pxelinux.cfg/default"
        return 0
    fi
    
    mkdir -p "$TFTP_ROOT/bios/pxelinux.cfg"
    
    cat > "$TFTP_ROOT/bios/pxelinux.cfg/default" <<EOF
# PXELINUX Boot Menu
# Generated by pxe-server installer

DEFAULT menu.c32
PROMPT 0
TIMEOUT 0

MENU TITLE Ubuntu PXE Boot Menu
MENU COLOR border       30;44   #40ffffff #a0000000 std
MENU COLOR title        1;36;44 #9033ccff #a0000000 std
MENU COLOR sel          7;37;40 #e0ffffff #20ffffff all
MENU COLOR unsel        37;44   #50ffffff #a0000000 std

LABEL ubuntu
    MENU LABEL Ubuntu 24.04 Desktop (NFS Boot)
    MENU DEFAULT
    KERNEL /boot/casper/vmlinuz
    APPEND initrd=/boot/casper/initrd boot=casper netboot=nfs nfsroot=$SERVER_IP:$PXE_ROOT ip=dhcp quiet splash ---
EOF
    
    log_success "PXELINUX configuration written"
}

# ═══════════════════════════════════════════════════════════════════════════════
# GRUB Configuration (UEFI)
# ═══════════════════════════════════════════════════════════════════════════════

write_grub_cfg() {
    info "Writing GRUB configuration for UEFI boot..."
    
    if [[ -z "${SERVER_IP:-}" ]]; then
        detect_network_interface_and_ip
    fi
    
    if [[ "${DRY_RUN:-false}" == true ]]; then
        info "[DRY-RUN] Would write grub.cfg"
        return 0
    fi
    
    cat > "$TFTP_ROOT/grub/grub.cfg" <<EOF
# GRUB Configuration for UEFI PXE Boot
# Generated by pxe-server installer

set default=0
set timeout=5

# Colors
set menu_color_normal=white/black
set menu_color_highlight=black/light-gray

menuentry "Ubuntu 24.04 Desktop (NFS Boot)" {
    linux /boot/casper/vmlinuz boot=casper netboot=nfs nfsroot=$SERVER_IP:$PXE_ROOT ip=dhcp quiet splash ---
    initrd /boot/casper/initrd
}

menuentry "Ubuntu 24.04 Desktop (NFS Boot - Safe Mode)" {
    linux /boot/casper/vmlinuz boot=casper netboot=nfs nfsroot=$SERVER_IP:$PXE_ROOT ip=dhcp nomodeset
    initrd /boot/casper/initrd
}
EOF
    
    log_success "GRUB configuration written"
}

# Check dnsmasq configuration
test_dnsmasq_config() {
    if dnsmasq --test 2>&1; then
        debug "dnsmasq configuration is valid"
        return 0
    else
        error "dnsmasq configuration has errors"
        return 1
    fi
}
