#!/usr/bin/env bash
# lib/kiosk.sh - Kiosk mode customization (squashfs injection)

# ═══════════════════════════════════════════════════════════════════════════════
# Kiosk Customization
# Unsquash filesystem, inject autostart scripts, repack
# ═══════════════════════════════════════════════════════════════════════════════

perform_kiosk_customization() {
    # Check if kiosk is enabled
    if [[ "${ENABLE_KIOSK:-true}" != true ]]; then
        info "Kiosk customization disabled (--no-kiosk)"
        return 0
    fi
    
    info "Performing kiosk customization..."
    
    # Find squashfs file
    local squash="$PXE_ROOT/casper/filesystem.squashfs"
    
    # Try alternate name if primary not found
    if [[ ! -f "$squash" ]]; then
        squash="$PXE_ROOT/casper/minimal.squashfs"
    fi
    
    if [[ ! -f "$squash" ]]; then
        warn "squashfs not found - skipping kiosk customization"
        warn "Looked for: $PXE_ROOT/casper/filesystem.squashfs"
        warn "        and: $PXE_ROOT/casper/minimal.squashfs"
        return 0
    fi
    
    if [[ "${DRY_RUN:-false}" == true ]]; then
        info "[DRY-RUN] Would customize squashfs: $squash"
        info "[DRY-RUN] Kiosk URL: $KIOSK_URL"
        info "[DRY-RUN] Kiosk User: $KIOSK_USER"
        return 0
    fi
    
    # ─────────────────────────────────────────────────────────────────────────
    # Unsquash the filesystem
    # ─────────────────────────────────────────────────────────────────────────
    
    local unsquash_dir="${WORK_DIR}/client-root"
    
    # Clean up any previous attempt (unsquashfs expects to create the dir)
    if [[ -d "$unsquash_dir" ]]; then
        rm -rf "$unsquash_dir"
    fi
    # Do NOT mkdir here - unsquashfs will fail if dir exists
    # mkdir -p "$unsquash_dir"
    
    info "Unsquashing filesystem (this may take a few minutes)..."
    if ! unsquashfs -d "$unsquash_dir" "$squash"; then
        abort "unsquashfs failed"
    fi
    
    # ─────────────────────────────────────────────────────────────────────────
    # Inject kiosk configuration
    # ─────────────────────────────────────────────────────────────────────────
    
    _inject_kiosk_autostart "$unsquash_dir"
    _inject_kiosk_policies "$unsquash_dir"
    _inject_kiosk_service "$unsquash_dir"
    _inject_kiosk_extensions "$unsquash_dir"
    
    # ─────────────────────────────────────────────────────────────────────────
    # Repack the squashfs
    # ─────────────────────────────────────────────────────────────────────────
    
    info "Repacking squashfs (this may take several minutes)..."
    
    # Backup original
    cp "$squash" "${squash}.backup" 2>/dev/null || true
    
    # Remove original and create new
    rm -f "$squash"
    if ! mksquashfs "$unsquash_dir" "$squash" -comp xz -b 1M -Xdict-size 100%; then
        # Restore backup on failure
        [[ -f "${squash}.backup" ]] && mv "${squash}.backup" "$squash"
        abort "mksquashfs failed"
    fi
    
    # Clean up
    rm -rf "$unsquash_dir"
    rm -f "${squash}.backup"
    
    log_success "Kiosk customization complete"
}

# ═══════════════════════════════════════════════════════════════════════════════
# Kiosk Service Injection (Systemd)
# ═══════════════════════════════════════════════════════════════════════════════

_inject_kiosk_service() {
    local rootdir="$1"
    local service_dir="$rootdir/etc/systemd/system"
    mkdir -p "$service_dir"
    
    info "Injecting Firefox systemd service..."
    
    local service_file="$service_dir/firefox-kiosk.service"
    
    cat > "$service_file" <<SYSTEMD
[Unit]
Description=Firefox Kiosk Mode
After=graphical.target

[Service]
Type=simple
User=${KIOSK_USER}
Group=${KIOSK_USER}
Environment=DISPLAY=:0
Environment=XAUTHORITY=/home/${KIOSK_USER}/.Xauthority
ExecStart=/usr/bin/firefox --kiosk --private-window ${KIOSK_URL} --new-instance
Restart=always
RestartSec=0
StartLimitIntervalSec=0

[Install]
WantedBy=graphical.target
SYSTEMD

    # Enable the service by creating the symlink
    local wants_dir="$service_dir/graphical.target.wants"
    mkdir -p "$wants_dir"
    ln -sfn "/etc/systemd/system/firefox-kiosk.service" "$wants_dir/firefox-kiosk.service"
    
    debug "Created systemd service at $service_file"
}

# ═══════════════════════════════════════════════════════════════════════════════
# Kiosk Autostart Script Injection (GNOME Settings)
# ═══════════════════════════════════════════════════════════════════════════════

_inject_kiosk_autostart() {
    local rootdir="$1"
    local profile_dir="$rootdir/etc/profile.d"
    mkdir -p "$profile_dir"
    
    local autostart_path="$profile_dir/99-kiosk-autostart.sh"
    info "Injecting kiosk autostart script..."
    
    # Create the autostart script with configurable options
    cat > "$autostart_path" <<KIOSK_SCRIPT
#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# Kiosk Mode Autostart Script
# Generated by pxe-server installer
# ═══════════════════════════════════════════════════════════════════════════════

KIOSK_USER="${KIOSK_USER}"
KIOSK_URL="${KIOSK_URL}"
KIOSK_SSID="${KIOSK_SSID:-}"
KIOSK_PASSWORD="${KIOSK_PASSWORD:-}"

# Configurable lockdown options
KIOSK_BLOCK_KEYS="${KIOSK_BLOCK_KEYS:-true}"
KIOSK_DISABLE_SHORTCUTS="${KIOSK_DISABLE_SHORTCUTS:-true}"
KIOSK_WAIT_GNOME="${KIOSK_WAIT_GNOME:-true}"
KIOSK_ENABLE_XBINDKEYS="${KIOSK_ENABLE_XBINDKEYS:-true}"

LOG="/tmp/kiosk-autostart.log"
echo "\$(date -Iseconds) Kiosk script start" >> "\$LOG"

# Only run in graphical session
[ -z "\$DISPLAY" ] && exit 0

# Only run once per session
LOCKFILE="/tmp/.kiosk-started-\$USER"
[ -f "\$LOCKFILE" ] && exit 0
touch "\$LOCKFILE"

# ───────────────────────────────────────────────────────────────────────────────
# Wait for GNOME Session (configurable)
# ───────────────────────────────────────────────────────────────────────────────

wait_for_gnome() {
    if [ "\$KIOSK_WAIT_GNOME" != "true" ]; then
        sleep 3
        return
    fi
    
    echo "\$(date -Iseconds) Waiting for GNOME session..." >> "\$LOG"
    local attempts=0
    while ! gsettings list-schemas >/dev/null 2>&1; do
        sleep 1
        attempts=\$((attempts + 1))
        [ \$attempts -gt 30 ] && break
    done
    echo "\$(date -Iseconds) GNOME session ready (or timeout)" >> "\$LOG"
}

# ───────────────────────────────────────────────────────────────────────────────
# WiFi Connection (if configured)
# ───────────────────────────────────────────────────────────────────────────────

connect_wifi() {
    if [ -n "\$KIOSK_SSID" ] && [ -n "\$KIOSK_PASSWORD" ]; then
        echo "\$(date -Iseconds) Connecting to WiFi: \$KIOSK_SSID" >> "\$LOG"
        nmcli device wifi connect "\$KIOSK_SSID" password "\$KIOSK_PASSWORD" 2>/dev/null || true
    fi
}

# ───────────────────────────────────────────────────────────────────────────────
# Disable GNOME Shortcuts (configurable)
# ───────────────────────────────────────────────────────────────────────────────

disable_shortcuts() {
    if [ "\$KIOSK_DISABLE_SHORTCUTS" != "true" ]; then
        echo "\$(date -Iseconds) Skipping shortcut disable (debug mode)" >> "\$LOG"
        return
    fi
    
    echo "\$(date -Iseconds) Disabling GNOME shortcuts" >> "\$LOG"
    gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "[]" 2>/dev/null || true
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "[]" 2>/dev/null || true
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "[]" 2>/dev/null || true
    gsettings set org.gnome.desktop.wm.keybindings close "[]" 2>/dev/null || true
    
    # Disable Alt+Tab (Switch Applications)
    gsettings set org.gnome.desktop.wm.keybindings switch-applications "[]" 2>/dev/null || true
    gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward "[]" 2>/dev/null || true
    gsettings set org.gnome.desktop.wm.keybindings switch-windows "[]" 2>/dev/null || true
    gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward "[]" 2>/dev/null || true
    
    # Disable Alt+Backtick (Switch Windows of Same App)
    gsettings set org.gnome.desktop.wm.keybindings switch-group "[]" 2>/dev/null || true
    gsettings set org.gnome.desktop.wm.keybindings switch-group-backward "[]" 2>/dev/null || true
    
    gsettings set org.gnome.settings-daemon.plugins.media-keys terminal "[]" 2>/dev/null || true
    gsettings set org.gnome.mutter overlay-key '' 2>/dev/null || true
}

# ───────────────────────────────────────────────────────────────────────────────
# Block Keys (configurable) - F1-F12, Super, Ctrl+Q, etc.
# ───────────────────────────────────────────────────────────────────────────────

block_keys() {
    if [ "\$KIOSK_BLOCK_KEYS" != "true" ]; then
        echo "\$(date -Iseconds) Skipping key blocking (debug mode)" >> "\$LOG"
        return
    fi
    
    echo "\$(date -Iseconds) Blocking dangerous keys" >> "\$LOG"
    # Block F1-F12 (keycodes 67-76, 95-96), Super (133-134)
    for keycode in 67 68 69 70 71 72 73 74 75 76 95 96 133 134; do
        xmodmap -e "keycode \$keycode = NoSymbol" 2>/dev/null || true
    done
}

# ───────────────────────────────────────────────────────────────────────────────
# Setup Shortcuts (Reload + Blocking)
# ───────────────────────────────────────────────────────────────────────────────

setup_shortcuts() {
    echo "\$(date -Iseconds) Setting up GNOME shortcuts" >> "\$LOG"
    
    local path_base="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings"
    
    # Define paths for custom shortcuts
    local p0="\$path_base/custom0/" # Reload
    local p1="\$path_base/custom1/" # Block Ctrl+Q
    local p2="\$path_base/custom2/" # Block Ctrl+W
    local p3="\$path_base/custom3/" # Block Ctrl+T
    local p4="\$path_base/custom4/" # Block Ctrl+Shift+I (Inspector)
    local p5="\$path_base/custom5/" # Block F12 (DevTools)
    local p6="\$path_base/custom6/" # Block Ctrl+L (Address Bar)
    local p7="\$path_base/custom7/" # Block Ctrl+I (Page Info)
    local p8="\$path_base/custom8/" # Block Ctrl+Shift+C (Inspector Picker)
    local p9="\$path_base/custom9/" # Block Ctrl+Shift+E (Network)
    local p10="\$path_base/custom10/" # Block Ctrl+Shift+W (Close Window)
    
    # 1. Reload Shortcut (Ctrl+Alt+R)
    local reload_cmd="/bin/true"
    local reload_bind=""
    
    if [ "\$KIOSK_ENABLE_XBINDKEYS" == "true" ]; then
        local reload_script="/home/\$KIOSK_USER/kiosk_reload.sh"
        cat > "\$reload_script" <<RELOAD
#!/bin/bash
pkill -u \$KIOSK_USER firefox; sleep 0.5; firefox --kiosk --private-window '\$KIOSK_URL' --new-instance &
RELOAD
        chmod +x "\$reload_script"
        chown "\$KIOSK_USER:\$KIOSK_USER" "\$reload_script"
        
        reload_cmd="\$reload_script"
        reload_bind="<Control><Alt>r"
    fi
    
    # 2. Blocking Dangerous Shortcuts
    local block_bind_q=""
    local block_bind_w=""
    local block_bind_t=""
    local block_bind_i=""
    local block_bind_f12=""
    local block_bind_l=""
    local block_bind_info=""
    local block_bind_c=""
    local block_bind_e=""
    local block_bind_sw=""
    
    if [ "\$KIOSK_BLOCK_KEYS" == "true" ]; then
        block_bind_q="<Control>q"
        block_bind_w="<Control>w"
        block_bind_t="<Control>t"
        block_bind_i="<Control><Shift>i"
        block_bind_f12="F12"
        block_bind_l="<Control>l"
        block_bind_info="<Control>i"
        block_bind_c="<Control><Shift>c"
        block_bind_e="<Control><Shift>e"
        block_bind_sw="<Control><Shift>w"
    fi
    
    # Apply Settings
    # Register the list of custom bindings
    gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['\$p0', '\$p1', '\$p2', '\$p3', '\$p4', '\$p5', '\$p6', '\$p7', '\$p8', '\$p9', '\$p10']" 2>/dev/null || true
    
    # Configure Reload
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p0 name 'Kiosk Reload'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p0 command "\$reload_cmd"
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p0 binding "\$reload_bind"
    
    # Configure Blocks
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p1 name 'Block Ctrl-Q'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p1 command '/bin/true'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p1 binding "\$block_bind_q"
    
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p2 name 'Block Ctrl-W'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p2 command '/bin/true'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p2 binding "\$block_bind_w"

    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p3 name 'Block Ctrl-T'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p3 command '/bin/true'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p3 binding "\$block_bind_t"
    
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p4 name 'Block Inspector'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p4 command '/bin/true'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p4 binding "\$block_bind_i"
    
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p5 name 'Block F12'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p5 command '/bin/true'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p5 binding "\$block_bind_f12"
    
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p6 name 'Block Ctrl-L'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p6 command '/bin/true'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p6 binding "\$block_bind_l"
    
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p7 name 'Block Ctrl-I'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p7 command '/bin/true'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p7 binding "\$block_bind_info"

    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p8 name 'Block Ctrl-Shift-C'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p8 command '/bin/true'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p8 binding "\$block_bind_c"

    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p9 name 'Block Ctrl-Shift-E'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p9 command '/bin/true'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p9 binding "\$block_bind_e"

    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p10 name 'Block Ctrl-Shift-W'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p10 command '/bin/true'
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$p10 binding "\$block_bind_sw"
}

# ───────────────────────────────────────────────────────────────────────────────
# Harden Desktop UI (Limit Interaction)
# ───────────────────────────────────────────────────────────────────────────────

harden_desktop() {
    echo "\$(date -Iseconds) Hardening desktop UI elements" >> "\$LOG"
    
    # Disable Ubuntu Dock Extension (Robust method)
    gnome-extensions disable ubuntu-dock@ubuntu.com 2>/dev/null || true
    
    # Enable Hide Top Bar Extension
    gnome-extensions enable hidetopbar@mathieu.bidon.ca 2>/dev/null || true
    
    # Fallbacks via gsettings
    gsettings set org.gnome.desktop.interface enable-hot-corners false 2>/dev/null || true
    gsettings set org.gnome.shell.extensions.dash-to-dock disable-overview-on-startup true 2>/dev/null || true
    gsettings set org.gnome.shell.extensions.dash-to-dock autohide true 2>/dev/null || true
    gsettings set org.gnome.shell.extensions.dash-to-dock dock-fixed false 2>/dev/null || true
    gsettings set org.gnome.shell.extensions.dash-to-dock intellihide false 2>/dev/null || true
    gsettings set org.gnome.shell.extensions.dash-to-dock height 0 2>/dev/null || true
    
    # Disable Desktop Icons (DING)
    gsettings set org.gnome.shell.extensions.ding show-home false 2>/dev/null || true
    gsettings set org.gnome.shell.extensions.ding show-trash false 2>/dev/null || true
    
    # GNOME Lockdown
    gsettings set org.gnome.desktop.lockdown disable-lock-screen true 2>/dev/null || true
    gsettings set org.gnome.desktop.lockdown disable-user-switching true 2>/dev/null || true
    gsettings set org.gnome.desktop.lockdown disable-log-out true 2>/dev/null || true
    
    # Restart Shell to apply changes (Required for some extensions/removals)
    # WARNING: On Wayland this terminates session. Kiosk usually runs on X11 or tolerates restart loop if config is idempotent.
    # We add a small delay and only run if session is established.
    (sleep 2; pkill -HUP gnome-shell) &
}

# ───────────────────────────────────────────────────────────────────────────────
# Prevent Screen Sleep
# ───────────────────────────────────────────────────────────────────────────────

prevent_sleep() {
    echo "\$(date -Iseconds) Disabling screen sleep" >> "\$LOG"
    xset s off 2>/dev/null || true
    xset -dpms 2>/dev/null || true
    xset s noblank 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing' 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing' 2>/dev/null || true
}

# ───────────────────────────────────────────────────────────────────────────────
# Main
# ───────────────────────────────────────────────────────────────────────────────

wait_for_gnome
connect_wifi
disable_shortcuts
block_keys
harden_desktop
setup_shortcuts
prevent_sleep

echo "\$(date -Iseconds) Kiosk setup complete" >> "\$LOG"
KIOSK_SCRIPT

    chmod +x "$autostart_path"
    debug "Autostart script created at $autostart_path"
}

# ═══════════════════════════════════════════════════════════════════════════════
# Kiosk Extensions Injection
# ═══════════════════════════════════════════════════════════════════════════════

_inject_kiosk_extensions() {
    local rootdir="$1"
    local extensions_dir="$rootdir/usr/share/gnome-shell/extensions"
    mkdir -p "$extensions_dir"
    
    info "Injecting GNOME Extensions..."
    
    # Install 'Hide Top Bar' from GitHub
    local ext_uuid="hidetopbar@mathieu.bidon.ca"
    local ext_path="$extensions_dir/$ext_uuid"
    
    if [ ! -d "$ext_path" ]; then
        info "Downloading Hide Top Bar extension..."
        local tmp_ext=$(mktemp -d)
        
        # Download master branch
        if wget -qO "$tmp_ext/extension.zip" "https://github.com/tuxor1337/hidetopbar/archive/refs/heads/master.zip"; then
            unzip -q "$tmp_ext/extension.zip" -d "$tmp_ext"
            
            # Dynamically find the extracted directory (e.g. hidetopbar-master)
            local src_dir=$(find "$tmp_ext" -mindepth 1 -maxdepth 1 -type d | head -n 1)
            
            if [ -n "$src_dir" ] && [ -d "$src_dir" ]; then
                mkdir -p "$ext_path"
                cp -r "$src_dir"/* "$ext_path/"
                
                # Compile Schemas
                if command -v glib-compile-schemas >/dev/null; then
                     info "Compiling schemas for $ext_uuid"
                     glib-compile-schemas "$ext_path/schemas" 2>/dev/null || warn "Failed to compile schemas for hidetopbar"
                else
                     warn "glib-compile-schemas not found - extension settings might fail"
                fi
                
                debug "Installed Hide Top Bar extension to $ext_path"
            else
                warn "Failed to extract Hide Top Bar (structure mismatch). Contents: $(ls "$tmp_ext")"
            fi
        else
            warn "Failed to download Hide Top Bar extension"
        fi
        
        rm -rf "$tmp_ext"
    else
        debug "Hide Top Bar extension already exists"
    fi
}

# ═══════════════════════════════════════════════════════════════════════════════
# Firefox Policies Injection
# ═══════════════════════════════════════════════════════════════════════════════

_inject_kiosk_policies() {
    local rootdir="$1"
    local policies_dir="$rootdir/usr/lib/firefox/distribution"
    mkdir -p "$policies_dir"
    
    local policies_file="$policies_dir/policies.json"
    info "Injecting Firefox policies..."
    
    cat > "$policies_file" <<POLICIES_JSON
{
    "policies": {
        "DisableAppUpdate": true,
        "DisableDeveloperTools": true,
        "DisableFormHistory": true,
        "DisablePasswordReveal": true,
        "DisablePocket": true,
        "DisablePrivateBrowsing": false,
        "DisableProfileImport": true,
        "DisableSystemAddonUpdate": true,
        "DisableTelemetry": true,
        "DNSOverHTTPS": {
            "Enabled": false
        },
        "DontCheckDefaultBrowser": true,
        "NoDefaultBookmarks": true,
        "OfferToSaveLogins": false,
        "OverrideFirstRunPage": "",
        "PasswordManagerEnabled": false,
        "Preferences": {
            "browser.tabs.warnOnClose": false,
            "browser.shell.checkDefaultBrowser": false,
            "browser.startup.homepage_override.mstone": "ignore",
            "datareporting.policy.dataSubmissionEnabled": false
        }
    }
}
POLICIES_JSON

    chmod 644 "$policies_file"
    debug "Firefox policies created at $policies_file"
}
