#!/usr/bin/env bash
# lib/kiosk.sh - Kiosk mode customization (squashfs injection)

# ═══════════════════════════════════════════════════════════════════════════════
# Kiosk Customization
# Unsquash filesystem, inject autostart scripts, repack
# ═══════════════════════════════════════════════════════════════════════════════

perform_kiosk_customization() {
    # Check if kiosk is enabled
    if [[ "${ENABLE_KIOSK:-true}" != true ]]; then
        info "Kiosk customization disabled (--no-kiosk)"
        return 0
    fi
    
    info "Performing kiosk customization..."
    
    # Find squashfs file
    local squash="$PXE_WEBROOT/casper/filesystem.squashfs"
    
    # Try alternate name if primary not found
    if [[ ! -f "$squash" ]]; then
        squash="$PXE_WEBROOT/casper/minimal.squashfs"
    fi
    
    if [[ ! -f "$squash" ]]; then
        warn "squashfs not found - skipping kiosk customization"
        warn "Looked for: $PXE_WEBROOT/casper/filesystem.squashfs"
        warn "        and: $PXE_WEBROOT/casper/minimal.squashfs"
        return 0
    fi
    
    if [[ "${DRY_RUN:-false}" == true ]]; then
        info "[DRY-RUN] Would customize squashfs: $squash"
        info "[DRY-RUN] Kiosk URL: $KIOSK_URL"
        info "[DRY-RUN] Kiosk User: $KIOSK_USER"
        return 0
    fi
    
    # ─────────────────────────────────────────────────────────────────────────
    # Unsquash the filesystem
    # ─────────────────────────────────────────────────────────────────────────
    
    local unsquash_dir="${WORK_DIR}/client-root"
    
    # Clean up any previous attempt
    if [[ -d "$unsquash_dir" ]]; then
        rm -rf "$unsquash_dir"
    fi
    mkdir -p "$unsquash_dir"
    
    info "Unsquashing filesystem (this may take a few minutes)..."
    if ! unsquashfs -d "$unsquash_dir" "$squash"; then
        abort "unsquashfs failed"
    fi
    
    # ─────────────────────────────────────────────────────────────────────────
    # Inject kiosk configuration
    # ─────────────────────────────────────────────────────────────────────────
    
    _inject_kiosk_autostart "$unsquash_dir"
    _inject_kiosk_policies "$unsquash_dir"
    
    # ─────────────────────────────────────────────────────────────────────────
    # Repack the squashfs
    # ─────────────────────────────────────────────────────────────────────────
    
    info "Repacking squashfs (this may take several minutes)..."
    
    # Backup original
    cp "$squash" "${squash}.backup" 2>/dev/null || true
    
    # Remove original and create new
    rm -f "$squash"
    if ! mksquashfs "$unsquash_dir" "$squash" -comp xz -b 1M -Xdict-size 100%; then
        # Restore backup on failure
        [[ -f "${squash}.backup" ]] && mv "${squash}.backup" "$squash"
        abort "mksquashfs failed"
    fi
    
    # Clean up
    rm -rf "$unsquash_dir"
    rm -f "${squash}.backup"
    
    log_success "Kiosk customization complete"
}

# ═══════════════════════════════════════════════════════════════════════════════
# Kiosk Autostart Script Injection
# ═══════════════════════════════════════════════════════════════════════════════

_inject_kiosk_autostart() {
    local rootdir="$1"
    local profile_dir="$rootdir/etc/profile.d"
    mkdir -p "$profile_dir"
    
    local autostart_path="$profile_dir/99-kiosk-autostart.sh"
    info "Injecting kiosk autostart script..."
    
    # Create the autostart script
    cat > "$autostart_path" <<KIOSK_SCRIPT
#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# Kiosk Mode Autostart Script
# Generated by pxe-server installer
# ═══════════════════════════════════════════════════════════════════════════════

KIOSK_USER="${KIOSK_USER}"
KIOSK_URL="${KIOSK_URL}"
KIOSK_SSID="${KIOSK_SSID:-}"
KIOSK_PASSWORD="${KIOSK_PASSWORD:-}"

# Only run in graphical session
[ -z "\$DISPLAY" ] && exit 0

# Only run once per session
LOCKFILE="/tmp/.kiosk-started-\$USER"
[ -f "\$LOCKFILE" ] && exit 0
touch "\$LOCKFILE"

# ───────────────────────────────────────────────────────────────────────────────
# WiFi Connection (if configured)
# ───────────────────────────────────────────────────────────────────────────────

connect_wifi() {
    if [ -n "\$KIOSK_SSID" ] && [ -n "\$KIOSK_PASSWORD" ]; then
        nmcli device wifi connect "\$KIOSK_SSID" password "\$KIOSK_PASSWORD" 2>/dev/null || true
    fi
}

# ───────────────────────────────────────────────────────────────────────────────
# Disable GNOME Shortcuts
# ───────────────────────────────────────────────────────────────────────────────

disable_shortcuts() {
    gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "[]" 2>/dev/null || true
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "[]" 2>/dev/null || true
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "[]" 2>/dev/null || true
    gsettings set org.gnome.desktop.wm.keybindings close "[]" 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.media-keys terminal "[]" 2>/dev/null || true
    gsettings set org.gnome.mutter overlay-key '' 2>/dev/null || true
}

# ───────────────────────────────────────────────────────────────────────────────
# Prevent Screen Sleep
# ───────────────────────────────────────────────────────────────────────────────

prevent_sleep() {
    xset s off 2>/dev/null || true
    xset -dpms 2>/dev/null || true
    xset s noblank 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing' 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing' 2>/dev/null || true
}

# ───────────────────────────────────────────────────────────────────────────────
# Launch Firefox in Kiosk Mode
# ───────────────────────────────────────────────────────────────────────────────

launch_firefox() {
    # Kill any existing Firefox instances
    pkill -u "\$USER" firefox 2>/dev/null || true
    sleep 0.5
    
    # Launch in kiosk mode
    export MOZ_NO_REMOTE=1
    firefox --kiosk --private-window "\$KIOSK_URL" --new-instance &
}

# ───────────────────────────────────────────────────────────────────────────────
# Main
# ───────────────────────────────────────────────────────────────────────────────

# Wait for desktop to fully load
sleep 3

connect_wifi
disable_shortcuts
prevent_sleep
launch_firefox
KIOSK_SCRIPT

    chmod +x "$autostart_path"
    debug "Autostart script created at $autostart_path"
}

# ═══════════════════════════════════════════════════════════════════════════════
# Firefox Policies Injection
# ═══════════════════════════════════════════════════════════════════════════════

_inject_kiosk_policies() {
    local rootdir="$1"
    local policies_dir="$rootdir/usr/lib/firefox/distribution"
    mkdir -p "$policies_dir"
    
    local policies_file="$policies_dir/policies.json"
    info "Injecting Firefox policies..."
    
    cat > "$policies_file" <<POLICIES_JSON
{
    "policies": {
        "DisableAppUpdate": true,
        "DisableFormHistory": true,
        "DisablePasswordReveal": true,
        "DisablePocket": true,
        "DisablePrivateBrowsing": false,
        "DisableProfileImport": true,
        "DisableSystemAddonUpdate": true,
        "DisableTelemetry": true,
        "DNSOverHTTPS": {
            "Enabled": false
        },
        "DontCheckDefaultBrowser": true,
        "NoDefaultBookmarks": true,
        "OfferToSaveLogins": false,
        "OverrideFirstRunPage": "",
        "PasswordManagerEnabled": false,
        "Preferences": {
            "browser.tabs.warnOnClose": false,
            "browser.shell.checkDefaultBrowser": false,
            "browser.startup.homepage_override.mstone": "ignore",
            "datareporting.policy.dataSubmissionEnabled": false
        }
    }
}
POLICIES_JSON

    chmod 644 "$policies_file"
    debug "Firefox policies created at $policies_file"
}
