#!/usr/bin/env bash
# lib/kiosk.sh - Kiosk mode customization (squashfs injection)

# ═══════════════════════════════════════════════════════════════════════════════
# Kiosk Customization
# Unsquash filesystem, inject autostart scripts, repack
# ═══════════════════════════════════════════════════════════════════════════════

perform_kiosk_customization() {
    # Check if kiosk is enabled
    if [[ "${ENABLE_KIOSK:-true}" != true ]]; then
        info "Kiosk customization disabled (--no-kiosk)"
        return 0
    fi
    
    info "Performing kiosk customization..."
    
    # Find squashfs file
    local squash="$PXE_ROOT/casper/filesystem.squashfs"
    
    # Try alternate name if primary not found
    if [[ ! -f "$squash" ]]; then
        squash="$PXE_ROOT/casper/minimal.squashfs"
    fi
    
    if [[ ! -f "$squash" ]]; then
        warn "squashfs not found - skipping kiosk customization"
        warn "Looked for: $PXE_ROOT/casper/filesystem.squashfs"
        warn "        and: $PXE_ROOT/casper/minimal.squashfs"
        return 0
    fi
    
    if [[ "${DRY_RUN:-false}" == true ]]; then
        info "[DRY-RUN] Would customize squashfs: $squash"
        info "[DRY-RUN] Kiosk URL: $KIOSK_URL"
        info "[DRY-RUN] Kiosk User: $KIOSK_USER"
        return 0
    fi
    
    # ─────────────────────────────────────────────────────────────────────────
    # Unsquash the filesystem
    # ─────────────────────────────────────────────────────────────────────────
    
    local unsquash_dir="${WORK_DIR}/client-root"
    
    # Clean up any previous attempt (unsquashfs expects to create the dir)
    if [[ -d "$unsquash_dir" ]]; then
        rm -rf "$unsquash_dir"
    fi
    # Do NOT mkdir here - unsquashfs will fail if dir exists
    # mkdir -p "$unsquash_dir"
    
    info "Unsquashing filesystem (this may take a few minutes)..."
    if ! unsquashfs -d "$unsquash_dir" "$squash"; then
        abort "unsquashfs failed"
    fi
    
    # ─────────────────────────────────────────────────────────────────────────
    # Inject kiosk configuration
    # ─────────────────────────────────────────────────────────────────────────
    
    _inject_kiosk_autostart "$unsquash_dir"
    _inject_kiosk_policies "$unsquash_dir"
    
    # ─────────────────────────────────────────────────────────────────────────
    # Repack the squashfs
    # ─────────────────────────────────────────────────────────────────────────
    
    info "Repacking squashfs (this may take several minutes)..."
    
    # Backup original
    cp "$squash" "${squash}.backup" 2>/dev/null || true
    
    # Remove original and create new
    rm -f "$squash"
    if ! mksquashfs "$unsquash_dir" "$squash" -comp xz -b 1M -Xdict-size 100%; then
        # Restore backup on failure
        [[ -f "${squash}.backup" ]] && mv "${squash}.backup" "$squash"
        abort "mksquashfs failed"
    fi
    
    # Clean up
    rm -rf "$unsquash_dir"
    rm -f "${squash}.backup"
    
    log_success "Kiosk customization complete"
}

# ═══════════════════════════════════════════════════════════════════════════════
# Kiosk Autostart Script Injection
# ═══════════════════════════════════════════════════════════════════════════════

_inject_kiosk_autostart() {
    local rootdir="$1"
    local profile_dir="$rootdir/etc/profile.d"
    mkdir -p "$profile_dir"
    
    local autostart_path="$profile_dir/99-kiosk-autostart.sh"
    info "Injecting kiosk autostart script..."
    
    # Create the autostart script with configurable options
    cat > "$autostart_path" <<KIOSK_SCRIPT
#!/bin/bash
# ═══════════════════════════════════════════════════════════════════════════════
# Kiosk Mode Autostart Script
# Generated by pxe-server installer
# ═══════════════════════════════════════════════════════════════════════════════

KIOSK_USER="${KIOSK_USER}"
KIOSK_URL="${KIOSK_URL}"
KIOSK_SSID="${KIOSK_SSID:-}"
KIOSK_PASSWORD="${KIOSK_PASSWORD:-}"

# Configurable lockdown options
KIOSK_BLOCK_KEYS="${KIOSK_BLOCK_KEYS:-true}"
KIOSK_DISABLE_SHORTCUTS="${KIOSK_DISABLE_SHORTCUTS:-true}"
KIOSK_WAIT_GNOME="${KIOSK_WAIT_GNOME:-true}"
KIOSK_ENABLE_XBINDKEYS="${KIOSK_ENABLE_XBINDKEYS:-true}"

LOG="/tmp/kiosk-autostart.log"
echo "\$(date -Iseconds) Kiosk script start" >> "\$LOG"

# Only run in graphical session
[ -z "\$DISPLAY" ] && exit 0

# Only run once per session
LOCKFILE="/tmp/.kiosk-started-\$USER"
[ -f "\$LOCKFILE" ] && exit 0
touch "\$LOCKFILE"

# ───────────────────────────────────────────────────────────────────────────────
# Wait for GNOME Session (configurable)
# ───────────────────────────────────────────────────────────────────────────────

wait_for_gnome() {
    if [ "\$KIOSK_WAIT_GNOME" != "true" ]; then
        sleep 3
        return
    fi
    
    echo "\$(date -Iseconds) Waiting for GNOME session..." >> "\$LOG"
    local attempts=0
    while ! gsettings list-schemas >/dev/null 2>&1; do
        sleep 1
        attempts=\$((attempts + 1))
        [ \$attempts -gt 30 ] && break
    done
    echo "\$(date -Iseconds) GNOME session ready (or timeout)" >> "\$LOG"
}

# ───────────────────────────────────────────────────────────────────────────────
# WiFi Connection (if configured)
# ───────────────────────────────────────────────────────────────────────────────

connect_wifi() {
    if [ -n "\$KIOSK_SSID" ] && [ -n "\$KIOSK_PASSWORD" ]; then
        echo "\$(date -Iseconds) Connecting to WiFi: \$KIOSK_SSID" >> "\$LOG"
        nmcli device wifi connect "\$KIOSK_SSID" password "\$KIOSK_PASSWORD" 2>/dev/null || true
    fi
}

# ───────────────────────────────────────────────────────────────────────────────
# Disable GNOME Shortcuts (configurable)
# ───────────────────────────────────────────────────────────────────────────────

disable_shortcuts() {
    if [ "\$KIOSK_DISABLE_SHORTCUTS" != "true" ]; then
        echo "\$(date -Iseconds) Skipping shortcut disable (debug mode)" >> "\$LOG"
        return
    fi
    
    echo "\$(date -Iseconds) Disabling GNOME shortcuts" >> "\$LOG"
    gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "[]" 2>/dev/null || true
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "[]" 2>/dev/null || true
    gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "[]" 2>/dev/null || true
    gsettings set org.gnome.desktop.wm.keybindings close "[]" 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.media-keys terminal "[]" 2>/dev/null || true
    gsettings set org.gnome.mutter overlay-key '' 2>/dev/null || true
}

# ───────────────────────────────────────────────────────────────────────────────
# Block Keys (configurable) - F1-F12, Super, Ctrl+Q, etc.
# ───────────────────────────────────────────────────────────────────────────────

block_keys() {
    if [ "\$KIOSK_BLOCK_KEYS" != "true" ]; then
        echo "\$(date -Iseconds) Skipping key blocking (debug mode)" >> "\$LOG"
        return
    fi
    
    echo "\$(date -Iseconds) Blocking dangerous keys" >> "\$LOG"
    # Block F1-F12 (keycodes 67-76, 95-96), Super (133-134)
    for keycode in 67 68 69 70 71 72 73 74 75 76 95 96 133 134; do
        xmodmap -e "keycode \$keycode = NoSymbol" 2>/dev/null || true
    done
}

# ───────────────────────────────────────────────────────────────────────────────
# xbindkeys Reload Shortcut (Ctrl+Alt+R)
# ───────────────────────────────────────────────────────────────────────────────

setup_reload_shortcut() {
    if [ "\$KIOSK_ENABLE_XBINDKEYS" != "true" ]; then
        echo "\$(date -Iseconds) Skipping reload shortcut (debug mode)" >> "\$LOG"
        return
    fi
    
    echo "\$(date -Iseconds) Setting up Ctrl+Alt+R reload shortcut (GNOME)" >> "\$LOG"
    
    # Create the reload script
    local reload_script="/home/\$KIOSK_USER/kiosk_reload.sh"
    cat > "\$reload_script" <<RELOAD_SCRIPT
#!/bin/bash
pkill -u \$KIOSK_USER firefox; sleep 0.5; firefox --kiosk --private-window '\$KIOSK_URL' --new-instance &
RELOAD_SCRIPT
    chmod +x "\$reload_script"
    chown "\$KIOSK_USER:\$KIOSK_USER" "\$reload_script"
    
    # Configure GNOME custom keybinding
    local key_path="/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/"
    
    gsettings set org.gnome.settings-daemon.plugins.media-keys custom-keybindings "['\$key_path']" 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$key_path name 'Kiosk Reload' 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$key_path command "\$reload_script" 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.media-keys.custom-keybinding:\$key_path binding '<Control><Alt>r' 2>/dev/null || true
}

# ───────────────────────────────────────────────────────────────────────────────
# Prevent Screen Sleep
# ───────────────────────────────────────────────────────────────────────────────

prevent_sleep() {
    echo "\$(date -Iseconds) Disabling screen sleep" >> "\$LOG"
    xset s off 2>/dev/null || true
    xset -dpms 2>/dev/null || true
    xset s noblank 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing' 2>/dev/null || true
    gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'nothing' 2>/dev/null || true
}

# ───────────────────────────────────────────────────────────────────────────────
# Install and Enable Firefox Systemd User Service (auto-restart)
# ───────────────────────────────────────────────────────────────────────────────

setup_firefox_service() {
    local service_dir="/home/\$KIOSK_USER/.config/systemd/user"
    mkdir -p "\$service_dir"
    
    cat > "\$service_dir/firefox-kiosk.service" <<SYSTEMD
[Unit]
Description=Firefox Kiosk Mode
After=graphical-session.target

[Service]
Type=simple
Environment=DISPLAY=:0
ExecStart=/usr/bin/firefox --kiosk --private-window \$KIOSK_URL --new-instance
Restart=always
RestartSec=2

[Install]
WantedBy=default.target
SYSTEMD
    
    chown -R "\$KIOSK_USER:\$KIOSK_USER" "/home/\$KIOSK_USER/.config"
    
    # Enable and start the service
    sudo -u "\$KIOSK_USER" systemctl --user daemon-reload 2>/dev/null || true
    sudo -u "\$KIOSK_USER" systemctl --user enable firefox-kiosk.service 2>/dev/null || true
    sudo -u "\$KIOSK_USER" systemctl --user start firefox-kiosk.service 2>/dev/null || true
    
    echo "\$(date -Iseconds) Firefox systemd service enabled (auto-restart)" >> "\$LOG"
}

# ───────────────────────────────────────────────────────────────────────────────
# Main
# ───────────────────────────────────────────────────────────────────────────────

wait_for_gnome
connect_wifi
disable_shortcuts
block_keys
setup_reload_shortcut
prevent_sleep
setup_firefox_service

echo "\$(date -Iseconds) Kiosk setup complete" >> "\$LOG"
KIOSK_SCRIPT

    chmod +x "$autostart_path"
    debug "Autostart script created at $autostart_path"
}

# ═══════════════════════════════════════════════════════════════════════════════
# Firefox Policies Injection
# ═══════════════════════════════════════════════════════════════════════════════

_inject_kiosk_policies() {
    local rootdir="$1"
    local policies_dir="$rootdir/usr/lib/firefox/distribution"
    mkdir -p "$policies_dir"
    
    local policies_file="$policies_dir/policies.json"
    info "Injecting Firefox policies..."
    
    cat > "$policies_file" <<POLICIES_JSON
{
    "policies": {
        "DisableAppUpdate": true,
        "DisableFormHistory": true,
        "DisablePasswordReveal": true,
        "DisablePocket": true,
        "DisablePrivateBrowsing": false,
        "DisableProfileImport": true,
        "DisableSystemAddonUpdate": true,
        "DisableTelemetry": true,
        "DNSOverHTTPS": {
            "Enabled": false
        },
        "DontCheckDefaultBrowser": true,
        "NoDefaultBookmarks": true,
        "OfferToSaveLogins": false,
        "OverrideFirstRunPage": "",
        "PasswordManagerEnabled": false,
        "Preferences": {
            "browser.tabs.warnOnClose": false,
            "browser.shell.checkDefaultBrowser": false,
            "browser.startup.homepage_override.mstone": "ignore",
            "datareporting.policy.dataSubmissionEnabled": false
        }
    }
}
POLICIES_JSON

    chmod 644 "$policies_file"
    debug "Firefox policies created at $policies_file"
}
