#!/usr/bin/env bash
# lib/network_static.sh - Static IP configuration via netplan

# ═══════════════════════════════════════════════════════════════════════════════
# Static Network Configuration
# ═══════════════════════════════════════════════════════════════════════════════

# Configuration defaults
STATIC_IP="${STATIC_IP:-10.0.0.1/24}"
SKIP_NETWORK="${SKIP_NETWORK:-false}"

# ═══════════════════════════════════════════════════════════════════════════════
# Netplan Configuration
# ═══════════════════════════════════════════════════════════════════════════════

configure_static_ip() {
    if [[ "${SKIP_NETWORK:-false}" == true ]]; then
        info "Skipping network configuration (--skip-network)"
        return 0
    fi
    
    # Check if running on a system with netplan
    if ! command -v netplan &>/dev/null; then
        warn "netplan not found, skipping static IP configuration"
        warn "Please configure network manually"
        return 0
    fi
    
    # Ensure we have interface info
    if [[ -z "${DEFAULT_IF:-}" ]]; then
        detect_network_interface_and_ip
    fi
    
    local netplan_file="/etc/netplan/90-pxe-server.yaml"
    
    info "Configuring static IP: $STATIC_IP on $DEFAULT_IF"
    
    if [[ "${DRY_RUN:-false}" == true ]]; then
        info "[DRY-RUN] Would write netplan config to $netplan_file"
        info "[DRY-RUN] Interface: $DEFAULT_IF"
        info "[DRY-RUN] Static IP: $STATIC_IP"
        return 0
    fi
    
    # Backup existing netplan configs
    if [[ -d /etc/netplan ]]; then
        mkdir -p /etc/netplan/backup
        cp /etc/netplan/*.yaml /etc/netplan/backup/ 2>/dev/null || true
        debug "Backed up existing netplan configs"
    fi
    
    # Write new netplan configuration
    cat > "$netplan_file" <<EOF
# PXE Server Static IP Configuration
# Generated by pxe-server installer on $(date)
# To revert: rm $netplan_file && netplan apply

network:
  version: 2
  renderer: networkd
  
  ethernets:
    $DEFAULT_IF:
      dhcp4: false
      addresses:
        - $STATIC_IP
EOF

    # Set correct permissions
    chmod 600 "$netplan_file"
    
    log_success "Netplan configuration written: $netplan_file"
}

apply_netplan() {
    if [[ "${SKIP_NETWORK:-false}" == true ]]; then
        return 0
    fi
    
    if [[ "${DRY_RUN:-false}" == true ]]; then
        info "[DRY-RUN] Would run: netplan apply"
        return 0
    fi
    
    info "Applying netplan configuration..."
    
    # Generate first to check for errors
    if ! netplan generate 2>/dev/null; then
        error "Netplan configuration has errors"
        error "Check: cat /etc/netplan/90-pxe-server.yaml"
        return 1
    fi
    
    # Apply the configuration
    if netplan apply; then
        log_success "Network configuration applied"
        info "New IP: $STATIC_IP on $DEFAULT_IF"
    else
        error "Failed to apply netplan"
        error "Network may need manual configuration"
        return 1
    fi
}

# Combined function for the install step
configure_network() {
    configure_static_ip
    apply_netplan
}
