#!/usr/bin/env bash
# lib/nginx.sh - Nginx web server configuration

# ═══════════════════════════════════════════════════════════════════════════════
# Nginx Configuration
# ═══════════════════════════════════════════════════════════════════════════════

configure_nginx_site() {
    info "Configuring nginx..."
    
    if [[ "${DRY_RUN:-false}" == true ]]; then
        info "[DRY-RUN] Would write nginx config to $NGINX_SITE"
        info "[DRY-RUN] Would set up webroot at $PXE_WEBROOT"
        return 0
    fi
    
    # ─────────────────────────────────────────────────────────────────────────
    # Remove default site if it exists and conflicts
    # ─────────────────────────────────────────────────────────────────────────
    
    if [[ -f /etc/nginx/sites-enabled/default ]]; then
        debug "Removing default nginx site"
        rm -f /etc/nginx/sites-enabled/default
    fi
    
    # ─────────────────────────────────────────────────────────────────────────
    # Write PXE site configuration
    # ─────────────────────────────────────────────────────────────────────────
    
    cat > "$NGINX_SITE" <<'NGINX_EOF'
# ═══════════════════════════════════════════════════════════════════════════════
# PXE Server Nginx Configuration
# Generated by pxe-server installer
# ═══════════════════════════════════════════════════════════════════════════════

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    # Webroot for PXE files
    root /var/www/html/desktop/u2404;
    
    # Enable directory listing for debugging
    autoindex on;
    autoindex_exact_size off;
    autoindex_localtime on;

    # Main location
    location / {
        try_files $uri $uri/ =404;
    }

    # ───────────────────────────────────────────────────────────────────────────
    # Performance tuning for large file transfers
    # ───────────────────────────────────────────────────────────────────────────
    
    # Allow large uploads/downloads (squashfs can be several GB)
    client_max_body_size 5G;
    
    # Enable sendfile for efficient file serving
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    
    # Increase timeouts for large files
    send_timeout 300s;
    keepalive_timeout 300s;
    
    # ───────────────────────────────────────────────────────────────────────────
    # Caching headers for PXE boot files
    # ───────────────────────────────────────────────────────────────────────────
    
    location ~* \.(squashfs|vmlinuz|initrd)$ {
        add_header Cache-Control "public, max-age=3600";
    }

    # ───────────────────────────────────────────────────────────────────────────
    # Error pages
    # ───────────────────────────────────────────────────────────────────────────
    
    error_page 404 /errors/404.html;
    error_page 500 502 503 504 /errors/50x.html;

    location = /errors/404.html {
        internal;
        return 404 "PXE Server: File not found\n";
    }

    location = /errors/50x.html {
        internal;
        return 500 "PXE Server: Internal error\n";
    }
    
    # ───────────────────────────────────────────────────────────────────────────
    # Health check endpoint
    # ───────────────────────────────────────────────────────────────────────────
    
    location = /health {
        return 200 "OK\n";
        add_header Content-Type text/plain;
    }
}
NGINX_EOF

    # ─────────────────────────────────────────────────────────────────────────
    # Set permissions
    # ─────────────────────────────────────────────────────────────────────────
    
    info "Setting webroot permissions..."
    chown -R www-data:www-data /var/www/html || abort "Failed to chown webroot"
    chmod -R 755 /var/www/html || abort "Failed to chmod webroot"
    
    # ─────────────────────────────────────────────────────────────────────────
    # Test and reload nginx
    # ─────────────────────────────────────────────────────────────────────────
    
    info "Testing nginx configuration..."
    if ! nginx -t 2>&1; then
        abort "nginx configuration test failed"
    fi
    
    info "Reloading nginx..."
    if ! systemctl reload nginx; then
        # Try restart if reload fails
        if ! systemctl restart nginx; then
            abort "Failed to reload/restart nginx"
        fi
    fi
    
    log_success "nginx configured and reloaded"
}

# Test nginx configuration
test_nginx_config() {
    nginx -t 2>&1
}

# Check if nginx is serving the webroot
check_nginx_webroot() {
    local url="http://localhost/casper/"
    if curl -s -o /dev/null -w "%{http_code}" "$url" | grep -q "200\|301\|302"; then
        debug "nginx is serving webroot correctly"
        return 0
    else
        warn "nginx may not be serving webroot correctly"
        return 1
    fi
}
