# Interface information
interface=eth0,lo
bind-interfaces
domain=c-nergy.local

# --------------------------
# DHCP Settings
# --------------------------

# DHCP scope for clients
dhcp-range=192.168.0.170,192.168.0.200,255.255.255.0,2h

# Default gateway
dhcp-option=3,192.168.0.1

# DNS server (your PXE server)
dhcp-option=6,192.168.0.160

# DNS forwarder
server=8.8.8.8

# ----------------------
# TFTP Options
# ----------------------

# BIOS pxelinux boot
dhcp-boot=/bios/pxelinux.0,pxeserver,192.168.0.160

# Enable TFTP
enable-tftp

# TFTP root path
tftp-root=/tftp

# Architecture detection for UEFI x86_64
dhcp-match=set:efi-x86_64,option:client-arch,7

# UEFI bootloader
dhcp-boot=tag:efi-x86_64,grub/bootx64.efi

