server {
    listen 9000 default_server;
    listen [::]:9000 default_server;

    root /var/www/html;
    index index.html;

    # Allow directory listing (required for easy debugging)
    location / {
        autoindex on;
    }

    # Disable caching to ensure modules update instantly
    location ~* \.(xzm|cfg|ipxe|xz|img|bin)$ {
        add_header Cache-Control "no-store";
    }
}

